import Link from 'next/link';
import { ArrowRight, FileText, Zap, Shield, Sparkles } from 'lucide-react';

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 relative overflow-hidden transition-colors selection:bg-blue-200 dark:selection:bg-blue-900">
      
      {/* Background Decor */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-500/10 dark:bg-blue-500/5 blur-[120px] rounded-full pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-indigo-500/10 dark:bg-indigo-500/5 blur-[120px] rounded-full pointer-events-none" />

      {/* Hero Section */}
      <main className="flex-1 flex flex-col items-center justify-center px-4 sm:px-6 lg:px-8 text-center pt-24 pb-16 relative z-10">
        <div className="inline-flex items-center rounded-full border border-blue-200 dark:border-blue-900 bg-blue-50 dark:bg-blue-950/30 px-3 py-1 text-sm font-medium text-blue-800 dark:text-blue-300 mb-8 backdrop-blur-sm shadow-sm transition-all hover:bg-blue-100 dark:hover:bg-blue-900/50">
          <Sparkles className="h-4 w-4 mr-2" />
          <span>The next generation of resume building</span>
        </div>

        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6 max-w-4xl mx-auto drop-shadow-sm">
          Craft your perfect <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-indigo-600 dark:from-blue-400 dark:to-indigo-400">AI-driven</span> resume in minutes
        </h1>
        
        <p className="mt-4 text-xl md:text-2xl text-slate-600 dark:text-slate-400 max-w-2xl mx-auto mb-10 leading-relaxed">
          Stand out from the crowd with ATS-friendly, professionally designed resumes generated by advanced artificial intelligence.
        </p>

        <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto mt-2">
          <Link 
            href="/signup" 
            className="group inline-flex items-center justify-center rounded-xl bg-blue-600 px-8 py-4 text-sm font-semibold text-white shadow-lg shadow-blue-500/30 hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 transition-all hover:-translate-y-0.5"
          >
            Get Started for Free
            <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
          </Link>
          <Link 
            href="/login" 
            className="inline-flex items-center justify-center rounded-xl bg-white dark:bg-slate-900 px-8 py-4 text-sm font-semibold text-slate-900 dark:text-white shadow-sm ring-1 ring-inset ring-slate-300 dark:ring-slate-700 hover:bg-slate-50 dark:hover:bg-slate-800 transition-all hover:-translate-y-0.5"
          >
            Log in
          </Link>
        </div>
      </main>

      {/* Feature Section */}
      <section className="py-20 bg-white/50 dark:bg-slate-900/50 backdrop-blur-md border-t border-slate-200/50 dark:border-slate-800/50 relative z-10 w-full flex justify-center">
        <div className="max-w-7xl px-4 sm:px-6 lg:px-8 grid grid-cols-1 md:grid-cols-3 gap-10 lg:gap-16 w-full">
          {[
            {
               title: 'Instant Generation',
               description: 'Watch your resume come to life instantly as the AI processes your data and formats it beautifully.',
               icon: <Zap className="h-6 w-6 text-yellow-500" />
            },
            {
               title: 'ATS-Friendly Formats',
               description: 'Our resumes are structured to pass Applicant Tracking Systems effortlessly without losing aesthetic appeal.',
               icon: <FileText className="h-6 w-6 text-green-500" />
            },
            {
               title: 'Secure & Private',
               description: 'Your data is securely stored, never shared without your permission, and completely under your control.',
               icon: <Shield className="h-6 w-6 text-blue-500" />
            }
          ].map((feature, i) => (
            <div key={i} className="flex flex-col items-center text-center p-6 rounded-2xl bg-white dark:bg-slate-800 shadow-sm border border-slate-100 dark:border-slate-700 hover:shadow-md transition-shadow">
              <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-50 dark:bg-slate-900/50 ring-1 ring-slate-200 dark:ring-slate-700 mb-6">
                {feature.icon}
              </div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">{feature.title}</h3>
              <p className="text-slate-600 dark:text-slate-400">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
